# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14511f2a3dac02d9ad1e2b19e5c919154884816083430fd8acd5eefe0196539865e9d9312f954d4c4f31cfcac7dbcb0b61eb1bb3c48b5c4897d256f1ee1eb146

test:
  secret_key_base: 384f038388b2b1e9bb9e8b2e1fbf9c98aacb39ffd2954f79956520db01e2ceb9813746ce8f9ff2992b7f2d138dd5b6aba5500447086649e91d66eeef34f9a9d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
